// examples/svelte/micro/src/pages/Imprint.svelte
<script lang="ts">
  import MainLayout from "../layouts/MainLayout.svelte";

  let { locale } = $props();
</script>

<MainLayout {locale}>
  {#snippet body()}
    <h1>Imprint</h1>
    <h2>Responsible</h2>
    <p>Texivia Example App<br>123 Example Street<br>12345 Example City</p>
    <h2>Contact</h2>
    <p>Email: example@texivia.dev</p>
  {/snippet}
</MainLayout>

// examples/vue/micro/src/pages/Imprint.vue
<script setup lang="ts">
import MainLayout from '../layouts/MainLayout.vue'

defineProps<{ locale: string }>()
</script>

<template>
  <MainLayout :locale="locale">
    <h1>Imprint</h1>
    <h2>Responsible</h2>
    <p>Texivia Example App<br>123 Example Street<br>12345 Example City</p>
    <h2>Contact</h2>
    <p>Email: example@texivia.dev</p>
  </MainLayout>
</template>
